version: 2
jobs:
  build:
    working_directory: ~/app-name
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
    # Install project dependencies
      - run:
        name: Install local dependencies
        command: npm install
    # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
    # Lint the source code
      - run:
          name: Linting
          command: npm run lint
    # Test the source code
      - run:
          name: Testing
          command: npm run -- ng test --watch false
